import React, { useState, useRef } from 'react';
import { supabase } from '../lib/supabaseClient';
import { 
  Search, Plus, Edit2, Trash2, X, Camera, 
  ChevronDown, ChevronUp, Calendar as CalIcon, User 
} from 'lucide-react';

export default function Employees({ employees, refreshData, logHistory }) {
  const [searchTerm, setSearchTerm] = useState('');
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingId, setEditingId] = useState(null);
  const [expandedId, setExpandedId] = useState(null);
  const fileInputRef = useRef(null);
  
  // Only track the fields we manually input.
  const [formData, setFormData] = useState({ name: '', photo: null });

  // --- Image Logic ---
  const handlePhotoUpload = (e) => {
    const file = e.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => setFormData({ ...formData, photo: reader.result });
      reader.readAsDataURL(file);
    }
  };

  const openModal = (emp = null) => {
    if (emp) { 
      setFormData({ name: emp.name, photo: emp.photo }); 
      setEditingId(emp.id); 
    } else { 
      setFormData({ name: '', photo: null }); 
      setEditingId(null); 
    }
    setIsModalOpen(true);
  };

  // --- Fixed Database Operations ---
  const handleSubmit = async (e) => {
    e.preventDefault();
    
    // Create the payload containing only the user-provided data.
    // We omit 'id' so Supabase can auto-increment it for new entries.
    const payload = {
      name: formData.name,
      photo: formData.photo
    };

    let response;

    if (editingId) {
      // UPDATE: Target the specific row using the existing ID
      response = await supabase
        .from('employees')
        .update(payload)
        .eq('id', editingId);
    } else {
      // INSERT: Send only name and photo; 'id' is generated by the DB
      response = await supabase
        .from('employees')
        .insert([payload]);
    }

    if (response.error) {
      alert("Database Error: " + response.error.message);
    } else {
      logHistory(`${editingId ? 'Updated' : 'Added'} personnel: ${formData.name}`);
      refreshData();
      setIsModalOpen(false);
    }
  };

  const handleDelete = async (id, name) => {
    if (window.confirm(`Permanently delete ${name}?`)) {
      const { error } = await supabase.from('employees').delete().eq('id', id);
      if (!error) {
        logHistory(`Deleted personnel: ${name}`);
        refreshData();
      }
    }
  };

  // --- Attendance View (Undertab) ---
  const AttendanceUndertab = () => (
    <div className="bg-slate-50 p-10 border-t border-slate-100 flex flex-col lg:flex-row gap-10 animate-in slide-in-from-top-2 duration-300">
      <div className="flex-1">
        <h4 className="text-xs font-black text-slate-400 uppercase tracking-widest mb-6 flex items-center">
          <CalIcon size={14} className="mr-2 text-indigo-500" /> Attendance: May 2026
        </h4>
        <div className="grid grid-cols-7 gap-3 max-w-sm">
          {Array.from({ length: 31 }, (_, i) => i + 1).map(day => (
            <div key={day} className={`h-10 w-10 flex items-center justify-center rounded-2xl text-[10px] font-black 
              ${[1, 4, 7, 11, 14, 18, 21].includes(day) ? 'bg-emerald-500 text-white shadow-lg' : 'bg-white border border-slate-200 text-slate-300'}`}>
              {day}
            </div>
          ))}
        </div>
      </div>
      <div className="lg:w-64 space-y-4">
        <div className="bg-slate-900 p-8 rounded-[2.5rem] text-white shadow-2xl">
          <p className="text-[10px] font-black uppercase opacity-50">Present Total</p>
          <h5 className="text-5xl font-black mt-2 tracking-tighter">7</h5>
        </div>
      </div>
    </div>
  );

  return (
    <div className="space-y-8 animate-in fade-in duration-700">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-black text-slate-900 tracking-tighter uppercase">Personnel Registry</h1>
          <p className="text-sm font-bold text-slate-400 mt-1">JAHS System Administration Dashboard</p>
        </div>
        <button onClick={() => openModal()} className="px-8 py-4 bg-slate-900 text-white rounded-[1.5rem] font-black text-xs uppercase tracking-[0.2em] shadow-2xl">
          <Plus size={18} className="mr-2 inline" /> New Entry
        </button>
      </div>

      <div className="bg-white border border-slate-200 rounded-[3rem] shadow-sm overflow-hidden">
        <div className="p-8 border-b border-slate-50 bg-slate-50/30">
          <div className="relative max-w-md w-full">
            <Search className="absolute left-5 top-1/2 -translate-y-1/2 text-slate-300" size={18} />
            <input 
              type="text" 
              placeholder="Filter by name..." 
              value={searchTerm} 
              onChange={(e) => setSearchTerm(e.target.value)} 
              className="w-full pl-14 pr-6 py-4 bg-white border border-slate-200 rounded-2xl text-sm font-bold outline-none" 
            />
          </div>
        </div>

        <table className="w-full text-left">
          <thead className="text-[10px] font-black uppercase text-slate-300 border-b border-slate-50 tracking-[0.2em]">
            <tr>
              <th className="px-12 py-6">Personnel Name</th>
              <th className="px-12 py-6 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-50">
            {employees.filter(e => e.name.toLowerCase().includes(searchTerm.toLowerCase())).map((emp) => (
              <React.Fragment key={emp.id}>
                <tr 
                  className={`group cursor-pointer transition-all ${expandedId === emp.id ? 'bg-indigo-50/40' : 'hover:bg-slate-50/50'}`}
                  onClick={() => setExpandedId(expandedId === emp.id ? null : emp.id)}
                >
                  <td className="px-12 py-6">
                    <div className="flex items-center gap-6">
                      <div className="w-16 h-16 rounded-[1.5rem] bg-white border-2 border-slate-50 overflow-hidden shadow-sm flex items-center justify-center p-1 group-hover:border-indigo-100 transition-all">
                        {emp.photo ? <img src={emp.photo} className="w-full h-full object-cover rounded-xl" /> : <User className="text-slate-100" size={32} />}
                      </div>
                      <p className="font-black text-slate-900 text-xl tracking-tight leading-tight">{emp.name}</p>
                    </div>
                  </td>
                  <td className="px-12 py-6 text-right space-x-3" onClick={(e) => e.stopPropagation()}>
                    <button onClick={() => openModal(emp)} className="p-3 text-slate-300 hover:text-indigo-600 hover:bg-white rounded-xl shadow-sm border border-transparent hover:border-slate-100 transition-all"><Edit2 size={16} /></button>
                    <button onClick={() => handleDelete(emp.id, emp.name)} className="p-3 text-slate-300 hover:text-rose-600 hover:bg-white rounded-xl shadow-sm border border-transparent hover:border-slate-100 transition-all"><Trash2 size={16} /></button>
                  </td>
                </tr>
                {expandedId === emp.id && (
                  <tr><td colSpan="2" className="p-0 border-none"><AttendanceUndertab /></td></tr>
                )}
              </React.Fragment>
            ))}
          </tbody>
        </table>
      </div>

      {isModalOpen && (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-md z-[70] flex items-center justify-center p-4">
          <div className="bg-white rounded-[3.5rem] shadow-2xl w-full max-w-md overflow-hidden animate-in zoom-in-95 duration-200">
            <div className="p-12 border-b border-slate-50 flex justify-between items-center bg-slate-50/50">
              <h2 className="text-3xl font-black text-slate-900 tracking-tighter">Personnel Data</h2>
              <button onClick={() => setIsModalOpen(false)} className="p-3 hover:bg-slate-200 rounded-full text-slate-300 transition-all"><X size={24} /></button>
            </div>
            <form onSubmit={handleSubmit} className="p-12 space-y-10">
              <div className="flex justify-center">
                <div onClick={() => fileInputRef.current.click()} className="w-44 h-44 rounded-[2.5rem] border-2 border-dashed border-slate-200 bg-slate-50 flex flex-col items-center justify-center cursor-pointer overflow-hidden hover:bg-slate-100 transition-all group relative">
                  {formData.photo ? <img src={formData.photo} className="w-full h-full object-cover" /> : <><Camera size={36} className="text-slate-200"/><span className="text-[10px] text-slate-400 font-black mt-3 tracking-[0.2em] uppercase">Set Photo</span></>}
                  <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 flex items-center justify-center transition-opacity text-white text-[10px] font-black uppercase tracking-[0.3em]">Change</div>
                </div>
                <input type="file" ref={fileInputRef} hidden accept="image/*" onChange={handlePhotoUpload} />
              </div>
              <div className="space-y-3">
                <label className="text-[10px] font-black text-slate-300 uppercase tracking-[0.2em] ml-2">Full Name</label>
                <input required type="text" value={formData.name} onChange={e => setFormData({...formData, name: e.target.value})} className="w-full px-8 py-5 bg-slate-50 border border-slate-200 rounded-[1.5rem] outline-none font-bold text-slate-800 text-lg shadow-inner" placeholder="Last Name, First Name" />
              </div>
              <button type="submit" className="w-full py-6 bg-indigo-600 text-white rounded-[2rem] font-black shadow-2xl hover:bg-indigo-700 transition-all uppercase tracking-[0.2em] text-xs">
                Save to Database
              </button>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}